version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - net

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - net

  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - net
    command: [ "redis-server", "--appendonly", "yes", "--appendfsync", "everysec" ]

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - net

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  net:
